version: '3.3'

services:
 
  builder-catalogue:
    build:
      dockerfile: Dockerfile.local
    image: builder-catalogue
    container_name: builder-catalogue
    restart: unless-stopped
    tty: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      API_URL: https://d16m5wbro86fg2.cloudfront.net
      SERVICE_TAGS: dev
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
