# stage 1 - build stage
FROM node:20-alpine as builder
 
WORKDIR /usr/src/app
 
COPY package*.json ./

RUN npm install nodemon

RUN npm install

COPY . .

RUN npm run build

# stage 2

FROM nginx:1.23.3-alpine-slim

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

COPY --from=builder /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]